### ISSUE TITLE
Update Webots to R2022a

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#124]
This requires converting some of the objects as well as fixing the x,y,z in the code.

**Comment by mrshu** [comment]
@Adman I guess this should be the priority then :slightly_smiling_face: 

Would you mind listing which parts do you think need to be done? I am sure we could split the work up somehow

**Comment by Adman** [comment]
They provided an algorithm for automatically converting the objects, so I think there is not too much to be done. I'll take this.
