### ISSUE TITLE
cannot import _controller.so Error 

### ISSUE THREAD

**Issue by Jenifen** [RoboCupJuniorTC/rcj-soccer-sim#126]
Error occured while i run the Simulation :

`ImportError: /usr/local/webots/lib/controller/python38/_controller.so: undefined symbol: _ZNK6webots3GPS14getSpeedVectorEvpen 
`

environment : webots 2022a, python38, ubuntu 20.04

**Comment by mrshu** [comment]
Hey @Jenifen,

Would you mind submitting this to https://github.com/cyberbotics/webots/? I believe they are much better suited to help you out with that.

Thanks!

**Comment by Jenifen** [comment]
Okay thanks
