### ISSUE TITLE
the simulation doesn't work

### ISSUE THREAD

**Issue by mohammadhosseinz** [RoboCupJuniorTC/rcj-soccer-sim#127]
The page simulator is parallel with gravity
It seems that the land has 90 degrees of error, in this "73bb7e534982e4f71f23637d832837fb92d655e0" commit.

**Comment by Adman** [comment]
@mohammadhosseinz Hello, what version of webots do you have? Could you please paste a screenshoot which describes you problem?

**Comment by mohammadhosseinz** [comment]
Hi, the last version. 189 is the commit number.
![jss](https://user-images.githubusercontent.com/50516049/150674932-17629038-9355-4306-b7db-dee4190c783b.jpg)
Thanks for your attention.

**Comment by Adman** [comment]
Alright, so you have the newest version of rcj-soccer-sim.

But how about Webots version? Is it R2021b, R2022a or something else?

**Comment by mohammadhosseinz** [comment]
we tested in macOS and windows in windows did not work in both version R2022a and R2021b but in mac is ok.

**Comment by Adman** [comment]
Do you have Windows 11? I tried running it on both Win11 and Win10 and it works.

**Comment by mohammadhosseinz** [comment]
tested on windows 7

**Comment by Adman** [comment]
Not sure what might have caused the problem. Do you have Win10/11 available?

**Comment by mohammadhosseinz** [comment]
problem solved😄
I noticed this problem when I run version 2 with webots version 2021 b
thank you for your attention🙏

**Comment by mrshu** [comment]
Thanks for getting back to us @mohammadhosseinz !
