### ISSUE TITLE
Auto gameplay pipeline 

### ISSUE THREAD

**Issue by aquahika** [RoboCupJuniorTC/rcj-soccer-sim#17]
Pack in docker?
Input several student's .py files and output game playback video and statistics.

**Comment by aquahika** [comment]
Running a webots on Docker is introduced at the official website:
https://www.cyberbotics.com/doc/guide/installation-procedure#installing-the-docker-image

On my environment with nvidia GPU, after installing nvidia-docker2 package it works well: 
![image](https://user-images.githubusercontent.com/2618822/102357070-4efffe80-3ff1-11eb-90c0-4ff4127df897.png)

**Comment by dbscoach** [comment]
Is there any easy way to run this headless without losing GPU acceleration? I tried and failed...

**Comment by mrshu** [comment]
@dbscoach @aquahika We should probably get together and figure out whether we can actually use GPU acceleration. I am happy to provide a server for testing purposes as well, if that would be of any help.

Would something like that work for you?

Thanks!
