### ISSUE TITLE
Template for participants

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#31]
@mrshu @felipenmartins I was thinking that we could provide some template for participants. PR https://github.com/RoboCupJuniorTC/webots-soccer-sim-playground/pull/30/ contains demo programs, where we are using this template as well.

```python
###### REQUIRED in order to import abstract robot class
import sys
from pathlib import Path
sys.path.append(str(Path('.').absolute().parent))
from rcj_soccer_player_b1 import rcj_soccer_robot, utils
######

import math

# Feel free to import other built-in libraries here
# You can import also other helper scripts that you create


class MyRobot(rcj_soccer_robot.RCJSoccerRobot):
    def run(self):
        while self.robot.step(rcj_soccer_robot.TIME_STEP) != -1:
            if self.is_new_data():
                # READ NEW DATA FROM SUPERVISOR
                data = self.get_new_data()

                # WRITE YOUR CODE HERE


my_robot = MyRobot()
my_robot.run()
```

**Comment by mrshu** [comment]
@Adman I believe the vast majority of participants will base their work off of the demo programs you've put together in #30. If they happen to contain a template like this, there is a good chance many of them will just include it in their programs.

That said, I think it makes a ton of sense and I would extend the comment a bit to say that the code shared among robots can be put into modules that are in the parent directory, much like `abstract_robot` in your example.

**Comment by mrshu** [comment]
@Adman the files currently essentially look like this, right?

**Comment by Adman** [comment]
@mrshu Yeah, like this. The only difference are robots B1 and Y1, which do not contain Path hacks.
