### ISSUE TITLE
Pass ball's speed in a message from supervisor

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#34]
So that robot's controller can measure where the ball is located after certain amount of time.

Does this make sense to you?

**Comment by mrshu** [comment]
> So that robot's controller can measure where the ball is located after certain amount of time.

I am not sure I get this @Adman, the robot's controller gets the position of the ball at each tick, couldn't it compute its speed on its own?

**Comment by Adman** [comment]
Ah, let's close this, wasn't aware that it can be computed in each tick.
