### ISSUE TITLE
Halftimes

### ISSUE THREAD

**Issue by mrshu** [RoboCupJuniorTC/rcj-soccer-sim#4]
@Adman I guess we'll have to figure this out somehow in the end

**Comment by mrshu** [comment]
My current thinking around halftimes is as follows:

1. Run the first half
2. Figure out who kicked off the first in the first half
```bash
$ cat The_Blues_vs_The_Yellows-2021-01-02T11:48:24.890235Z.jsonl | grep KICKOFF | head -n 1 | jq .
"Y3"
```
3. Add an env variable (something like `RCJ_SOCCERSIM_KICKOFF_TEAM`) and set to B  in case yellow was kicking off in the first half and Y otherwise
4. Run the second half similarly to the first one

**Comment by Adman** [comment]
@mrshu I think we can close this one. If we find a better solution we can reopen it later.
