### ISSUE TITLE
Deal with robots that enter infinite loop

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#50]
When a robot is not responding, end the match and the opponent wins 10:0.

**Comment by mrshu** [comment]
How do you think we should go about doing this?

Here is what I could see as "doable but certainly not nice":
- Overload `get_new_data` and make it emit something each second (to a named pipe or to some file -- something like a heartbeat)
- Have an outside checker that will take a look at all the processes/files and within some grace period (say each 5 or 10 seconds) check whether the heartbeat came in
- If it did not, end the match

Do you think something like that could work?

**Comment by Adman** [comment]
Yes, this is probably the best doable solution at the moment. We should probably mention this in the rules - let's discuss it in the meeting.

**Comment by mrshu** [comment]
@Adman Guess what, it's got a very simple solution in the end!

Seems like the home-take point is that we should have just asked...

https://github.com/cyberbotics/webots/issues/2859#issuecomment-800042125
