### ISSUE TITLE
Wrong robot respawn

### ISSUE THREAD

**Issue by ArterKrilOk** [RoboCupJuniorTC/rcj-soccer-sim#63]
Robot respawns with not zero velocity and rotation.

**Comment by mrshu** [comment]
Thanks for your report @ArterKrilOk!

Would you happen to have a minimal reproducible test case where this may happen? It would greatly help us figuring out where the bug is as well as figuring out the fix.

Thanks!

**Comment by Adman** [comment]
Hello @ArterKrilOk. Could you please test if this problem occurs with the newest software? I'll close this issue for now. If you run into similar problem, feel free to reopen this issue.
