### ISSUE TITLE
Notify robots that goal was scored

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#73]
Via the message sent by supervisor

**Comment by mrshu** [comment]
@Adman Is there a particular usecase in which this would be valuable? I don't seem to see it and so I am pretty sure I must be missing something :)

**Comment by Adman** [comment]
In real robocup, the teams mostly turn off their robot/program when the goal is scored in order to reset stuff and run the program from beginning. This might be the case here as well, so teams want to re-initialize some variables and so forth.
Of course it's possible by checking the x,y position of the ball, but it's not a nice way how to do it :)
