### ISSUE TITLE
Lack-of-Progress the ball if it leaves the field or increase tick rate so it doesn't anymore

### ISSUE THREAD

**Issue by dbscoach** [RoboCupJuniorTC/rcj-soccer-sim#77]
Ball can pass through the wall if it does so in one tick and eventually score a goal (due to moving sideways enough to be behind the goal line)

**Comment by mrshu** [comment]
I'd be still interested in understanding better how this may happen (passing through the wall). Is it possible we've messed something up in the world definition?
