### ISSUE TITLE
Lack of progress: add randomness

### ISSUE THREAD

**Issue by Adman** [RoboCupJuniorTC/rcj-soccer-sim#79]
Choose randomly from 2 or 3 nearest/furthest neutral spots.

**Comment by mrshu** [comment]
@Adman could we perhaps do it completely randomly? Is there any value in doing the nearest/furthest neutral spot?

**Comment by Adman** [comment]
Well, not sure if complete randomness is a good way to go. Imagine all robots being in one corner, lack of progress is called and the ball is moved to the furthest spot. It will take quite a lot of time for robots to get there and meanwhile another lack of progress might happen.
